version: '3'
services:
  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8080:3000
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
